#!/bin/bash

# Update system with latest patches
export JENKINS_HOME=$HOME
export JENKINS_SLAVE_AGENT_PORT=50000
export JENKINS_USER=$(whoami)
export JENKINS_GROUP=jenkins
export JENKINS_UID=998
export JENKINS_GID=998
export JENKINS_INSTALL=/usr/share/jenkins
export COPY_REFERENCE_FILE_LOG=$JENKINS_HOME/copy_reference_file.log

export JENKINS_UC=https://updates.jenkins.io



